### PR TITLE
Fixes dupe bug

### PR DESCRIPTION
**Pull request by Halfdeaf**
Fixes https://github.com/NillerMedDild/Enigmatica5/issues/391

### CODE REVIEW

**Comment by Halfdeaf** [comment]
I reduced the number of guaranteed shards from 2 to 1

**Comment by MuteTiefling** [comment]
This doesn't really fix the dupe, however.

1 Prismarine Crystal turns into 1 Prismarine shard (plus bonus), some glowstone dust, and some quartz.

Those shards can then be converted back to crystals for the low cost of a bit of RF with Mekanism. Since there's a chance to get extra shards still, it still is 'duping' them, effectively, as well as creating infinite glowstone and quartz from that one input plus a bit of RF.

It would likely be better handled on the mekanism recipe side by either removing the enriching recipe altogether, making it turn 9 primarine into 1, or otherwise requiring some extra material input. 

Personally, I think it would be best to convert it to a metallurgic infuser recipe that combines diamond and shards to make crystals. So you can convert an overworld resource (diamond) into nether resources (glowstone, quartz) with that bit of prismarine acting as a catalyst.

**Comment by Halfdeaf** [comment]
The biggest issue in my eyes was how easy it was to dupe. These are relatively easily farmable materials so personally I don't mind if you can get a bit extra this way. If this was for an expert version I would feel differently but we'll see what Niller thinks

**Comment by Halfdeaf** [comment]
Having a bit of a brainfart here, you are correct on the quartz, glowstone stuff

**Comment by NielsPilgaard** [comment]
Thanks for the bug report and PR!

I'm currently thinking I will remove the Enrichment recipe, but I need to think it over :)

**Comment by Halfdeaf** [comment]
Looks like it's actually jaopca adding the recipe because prismarine shards have a forge:dusts tag so I say just remove it

**Comment by NielsPilgaard** [comment]
Perfect, thank you. You have verified that it works I assume? :)

**Comment by Halfdeaf** [comment]
Yep, checked it in world and the recipe is gone from JEI

**Comment by Halfdeaf** [comment]
note that another unrelated commit accidentally slipped into this PR it was meant to go into another

**Comment by NielsPilgaard** [comment]
I saw, nice change :)

**Pull request merged**
