### PR TITLE
Fix for create ore washing for copper

### PR DESCRIPTION
**Pull request by theboo**
fixes copper nugget portion of #389 and #385

### CODE REVIEW

**Comment by theboo** [comment]
this works perfect on single player... doesnt seem to work on my test server? maybe you can take a look?

**Review by NielsPilgaard — CHANGES_REQUESTED** [review]
This shouldn't be needed, as the json recipe you provided in the other commit overwrites the create nugget recipe :)

**Review by NielsPilgaard — APPROVED** [review]
Nice!

**Comment by NielsPilgaard** [comment]
I just did the change myself to test the PR :)

**Pull request merged**
