### PR TITLE
Add Linux instructions to install E5 to README

### PR DESCRIPTION
**Pull request by kharann**
It also works on windows and mac. Just a general way to install with MulitMC which works pretty well!

### CODE REVIEW

**Comment by Darkere** [comment]
The Twitch search is not yet available on the stable multimc build.

**Comment by kharann** [comment]
Ahh, saw latest release on their GitHub page so I assumed that it was stable. Telling users to enable development version in the instruction might be a hassle so the solution is just to wait for multimc to release a stable version

**Comment by NielsPilgaard** [comment]
Thanks! Will merge once it's out of development :)

**Comment by dthompkins** [comment]
I downloaded the zip file from cursforge and installed that that way, it's one more step but doesn't depend on the Twitch integration on multimc

**Pull request merged**
