### PR TITLE
Added water soil, kelp, IE hemp and Occultism demon fruit to botany pots.

### PR DESCRIPTION
**Pull request by hvdklauw**
Growth ticks might need some tweaking, didn't want them to grow too fast.

### CODE REVIEW

**Comment by NielsPilgaard** [comment]
Thanks for the PR! :D
May I have a picture of how the water as soil looks in the Botany Pot please? :)

**Comment by theboo** [comment]
tested it out... the stained glass doesnt look too bad but i am quite partial to the quark blue cave crystal xD here's a few i tried out... another option might be to make a block with kube and have Rid give it a nice animated water texture :D 

minecraft:blue_stained_glass - https://gyazo.com/ce1bdb6c611451d5b9cbb6b62b919871 (lighting glitch/flickering was due to optifine, isnt present after disabling and i disabled for all the other gifs)

quark:blue_crystal - https://gyazo.com/c5aa50c0e6ceec0d3d1420d2656f4ddc

connectedglass:clear_glass_blue - https://gyazo.com/15394b762aba6de8d2fc84f44cc4e1bb

connectedglass:scratched_glass_blue - https://gyazo.com/32669b7fe41367a79350516cee2b6c38

**Comment by hvdklauw** [comment]
Thanks, was sleeping.

Yeah water itself doesn't work and didn't want to use a modded block because then things would break if the mod got removed.

But hey, feel free to make a custom block or use another. I felt like the blue stained glass looked close enough if you saw it in passing. The kelp is growing on top so it's never gonna be 100% accurate.

**Comment by NielsPilgaard** [comment]
I also like the Quark blue crystal, gonna change it to that - Everything looks good, ty :D

**Pull request merged**
