### PR TITLE
Recipes, Tags, and Lang Entry

### PR DESCRIPTION
**Pull request by Ridanisaurus**
Added:
- 4x Shapeless Recipes for the Nature's Aura tokens.
- Tag Group `minecraft:meats` to allow the input of any of the 4 types of raw meat. This is similar to how `minecraft:fishes` is a thing.
- Lang entry for Project Vibrant Journeys Ocean Starfish as it was missing, and the entities have `entity.projectvibrantjourneys.starfish_ocean` in-game

### CODE REVIEW

**Comment by Ridanisaurus** [comment]
Damn it. The files I uploaded are from the current 0.6.0 KubeJS instead of the Dev KubeJS. Some stuff will be overwritten. Sorry. 
If you want cancel this request, and I can send a new one using the 0.6.1 KubeJS files instead.

**Comment by NielsPilgaard** [comment]
I will copy-paste the changes in, if that's okay with you :)

**Comment by NielsPilgaard** [comment]
Hmm, aren't there more NA Ritual of the Forest recipes?

**Comment by Ridanisaurus** [comment]
As far as I know, only those. However, I only played a little with this mod, and those are the only 4 that I could tell which required growing a tree. If you find or remember any, let me know, and I'll send them over.

**Comment by NielsPilgaard** [comment]
Alright cool, thanks!

**Pull request closed without merging**
